In [1288]:
import numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x)) 

def relu(x):
    return x * (x > 0)

In [1289]:
class Neuron:
    def __init__(self, weight, bias):
        self.weight = weight
        self.bias = bias
        
    def feedforward(self, inputs, act_type):
        total = np.dot(self.weight, inputs) + self.bias
        if act_type == 0:
            return sigmoid(total)
        elif act_type == 1:
            return softmax(total)
        elif act_type == 2:
            return relu(total)

In [1290]:
class Neural_Net:
    def __init__(self, h_num, o_num, i_weight, o_weight, i_bias, o_bias):
        self.i_weight = i_weight
        self.o_weight = o_weight
        self.i_bias = i_bias
        self.o_bias = o_bias
        self.h_num = h_num
        self.o_num = o_num
        self.hidden = []
        self.output = []
        for i in range(h_num):
            self.hidden.append(Neuron(i_weight[i,:], i_bias[i]))
        for i in range(o_num):
            self.output.append(Neuron(o_weight[i,:], o_bias[i]))
    def feedforward(self, i_data):
        o_hidden = []
        o_output = []
        for i in range(self.h_num):
            o_hidden.append(self.hidden[i].feedforward(i_data,0))
        for i in range(self.o_num):
            o_output.append(self.output[i].feedforward(o_hidden,0))
        return o_output, o_hidden
    def backpropagation(self, i_y, y_pred, h_value, i_x):
        h_field = np.matmul(np.matmul(deriv_loss(i_y,y_pred), deriv_pred(h_value,self.o_weight,self.o_bias)), deriv_hidden(i_x, self.i_weight, self.i_bias))
        o_field = np.matmul(np.transpose(deriv_loss(i_y,y_pred)), deriv_hidden(h_value, self.o_weight, self.o_bias))
        h_bias_field = h_field[len(h_field)-self.h_num:]
        h_field = np.reshape(h_field[0:len(h_field)-self.h_num], (self.h_num, len(i_x)))#h_field[0:len(h_field)-self.h_num].reshape[self.h_num, self.o_num]
        o_bias_field = o_field[len(o_field)-self.o_num:]
        o_field = np.reshape(o_field[0:len(o_field)-self.o_num], (self.o_num, self.h_num))
        
        print("dL/dPred",deriv_loss(i_y,y_pred))
        print("dPred/dH",deriv_pred(h_value,self.o_weight,self.o_bias))
        print("dH/dW",deriv_hidden(i_x, self.i_weight, self.i_bias))
        print("dPred/dW",deriv_hidden(h_value, self.o_weight, self.o_bias))
        print("\n")
        
        return h_field, o_field, h_bias_field, o_bias_field

In [1291]:
def deriv_sigmoid(x):
    fx = sigmoid(x)
    return fx * (1 - fx)

def deriv_loss(y_true, y_pred):
    return -2*(y_true - y_pred)

def deriv_pred(hidden, o_weight, o_bias):
    return o_weight * deriv_sigmoid(np.dot(o_weight, hidden) + o_bias)[:,None]

def deriv_hidden(i_data, i_weight, i_bias):
    n_dim = i_weight.shape[0]
    w_dim = i_weight.shape[1]
    derv = np.zeros((n_dim, n_dim * w_dim + n_dim))
    for i in range(0,n_dim):
        derv[i : i+1, i*w_dim : (i+1)*w_dim] = np.array(i_data) * deriv_sigmoid(np.dot(i_weight[i,:],i_data) + i_bias[i])
        derv[i : i+1, n_dim*w_dim+i : n_dim*w_dim+i+1] = deriv_sigmoid(np.dot(i_weight[i,:],i_data) + i_bias[i])
    return derv

In [1292]:
i_weight = np.array([[0.3,0.7],[0.1,0.2]])
o_weight = np.array([[0.4,0.3]])
i_bias = np.array([0.5,0.4])
o_bias = np.array([0.3])
#i_weight = np.array([[0.3,0.7],[0.1,0.2],[0.4,0.1],[0.2,0.5]])
#o_weight = np.array([[0.4,0.3,0.2,0.1]])
#i_bias = np.array([0.5,0.4,0.3,0.5])
#o_bias = np.array([1])
#i_data = np.array([[1,0,1,0],[1,0,1,1]])
i_data = np.array([
  [-2, -1, 1],  # Alice
  [25, 6, 0],   # Bob
  [17, 4, 0],   # Charlie
  [-15, -6, 1], # Diana
])

#x_i_weight = 2
#y_i_weight = 2
#i_weight = np.random.normal(size=(x_i_weight,y_i_weight))

#x_o_weight = 1
#y_o_weight = 2
#o_weight = np.random.normal(size=(x_o_weight,y_o_weight))

#x_i_bias = 1
#y_i_bias = 2
#i_bias = np.random.normal(size=(y_i_bias))

#x_o_bias = 1
#y_o_bias = 1
#o_bias = np.random.normal(size=(x_o_bias))

print(i_weight)
print(o_weight)
print(i_bias)
print(o_bias)

[[0.3 0.7]
 [0.1 0.2]]
[[0.4 0.3]]
[0.5 0.4]
[0.3]


In [1293]:
def train(i_weight, o_weight, i_bias, o_bias, i_data, learning_rate):
    epoch = 1000
    h_size = i_weight.shape[0]
    o_size = i_data.shape[1]
    n = i_data.shape[1]
    obs_n = i_data.shape[0]
    i_y = i_data[: , n-1:n]
    o_size = i_y.shape[1]
    i_x = i_data[: , 0:n-1]
    
    for j in range(epoch):
        loss = 0
        for i in range(0,obs_n):
            network = Neural_Net(h_size, o_size, i_weight, o_weight, i_bias, o_bias)
            pred_y, h_value = network.feedforward(i_x[i, :])
            h_field, o_field, h_bias_field, o_bias_field = network.backpropagation(i_y[i], pred_y, h_value, i_x[i, :])
            i_weight, o_weight, i_bias, o_bias = gradient_descent(i_weight, o_weight, i_bias, o_bias, h_field, o_field, h_bias_field, o_bias_field, learning_rate)
            loss = loss + mse_loss(i_y[i], pred_y)
        print("Epoch %d loss: %.3f" % (epoch, loss))
    #return i_weight, o_weight, i_bias, o_bias
    
        
def gradient_descent(i_weight, o_weight, i_bias, o_bias, h_field, o_field, h_bias_field, o_bias_field, learning_rate):
    i_weight = i_weight - learning_rate * h_field
    o_weight = o_weight - learning_rate * o_field
    i_bias = i_bias - learning_rate * h_bias_field
    o_bias = o_bias - learning_rate * o_bias_field
    return i_weight, o_weight, i_bias, o_bias

def mse_loss(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

In [1294]:
train(i_weight, o_weight, i_bias, o_bias, i_data, 0.1)

dL/dPred [-0.72062401]
dPred/dH [[0.09219491 0.06914618]]
dH/dW [[-0.42781939 -0.2139097   0.          0.          0.2139097   0.        ]
 [ 0.          0.         -0.5        -0.25        0.          0.25      ]]
dPred/dW [[0.07145693 0.11524363 0.23048726]]


dL/dPred [1.47176835]
dPred/dH [[0.07874428 0.05992169]]
dH/dW [[1.35984359e-04 3.26362461e-05 0.00000000e+00 0.00000000e+00
  5.43937436e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.28358553e-01 1.02806053e-01
  0.00000000e+00 1.71343421e-02]]
dPred/dW [[0.1943576  0.19096934 0.19435866]]


dL/dPred [1.43349351]
dPred/dH [[0.07644637 0.05688613]]
dH/dW [[4.02734085e-03 9.47609611e-04 0.00000000e+00 0.00000000e+00
  2.36902403e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.30169820e-01 2.18863487e-01
  0.00000000e+00 5.47158718e-02]]
dPred/dW [[0.20297274 0.19122729 0.20302085]]


dL/dPred [-0.85729153]
dPred/dH [[0.08509309 0.0619095 ]]
dH/dW [[-4.34296385e-03 -1.73718554e-03  0.00000000e+00  0.00000000e+00
   

dL/dPred [0.73051042]
dPred/dH [[-0.14535797  0.16228172]]
dH/dW [[0.00196227 0.00046171 0.         0.         0.00011543 0.        ]
 [0.         0.         0.08942139 0.02104033 0.         0.00526008]]
dPred/dW [[0.23181708 0.001226   0.23184384]]


dL/dPred [-0.64166246]
dPred/dH [[-0.14030476  0.15250104]]
dH/dW [[-0.002115   -0.000846    0.          0.          0.000141    0.        ]
 [ 0.          0.         -0.07367392 -0.02946957  0.          0.00491159]]
dPred/dW [[3.07280838e-05 2.16823013e-01 2.17898551e-01]]


Epoch 1000 loss: 0.537
dL/dPred [-0.79581634]
dPred/dH [[-0.15426319  0.17100652]]
dH/dW [[-0.40961845 -0.20480923  0.          0.          0.20480923  0.        ]
 [ 0.          0.         -0.38011777 -0.19005889  0.          0.19005889]]
dPred/dW [[0.068859   0.17844403 0.23957726]]


dL/dPred [0.73102499]
dPred/dH [[-0.14805741  0.16882934]]
dH/dW [[4.06164807e-05 9.74795537e-06 0.00000000e+00 0.00000000e+00
  1.62465923e-06 0.00000000e+00]
 [0.00000000e+00 0.0000

dPred/dW [[1.89760256e-01 7.25161860e-05 1.89762273e-01]]


dL/dPred [-0.42542061]
dPred/dH [[-0.1944623   0.20801474]]
dH/dW [[-1.94930107e-04 -7.79720428e-05  0.00000000e+00  0.00000000e+00
   1.29953405e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.55855133e-03 -2.22342053e-03
   0.00000000e+00  3.70570089e-04]]
dPred/dW [[2.17628820e-06 1.67402552e-01 1.67464632e-01]]


Epoch 1000 loss: 0.269
dL/dPred [-0.60195726]
dPred/dH [[-0.2443084   0.26283306]]
dH/dW [[-0.33767169 -0.16883585  0.          0.          0.16883585  0.        ]
 [ 0.          0.         -0.30139455 -0.15069727  0.          0.15069727]]
dPred/dW [[0.04525642 0.1714942  0.21039049]]


dL/dPred [0.5101624]
dPred/dH [[-0.22013018  0.23933999]]
dH/dW [[1.17501764e-06 2.82004235e-07 0.00000000e+00 0.00000000e+00
  4.70007058e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.62972067e-04 3.91132960e-05
  0.00000000e+00 6.51888266e-06]]
dPred/dW [[1.90014772e-01 1.23869213e-06 1.90014781e-01]]


dL/dPred

dL/dPred [-0.31954865]
dPred/dH [[-0.19968648  0.21265181]]
dH/dW [[-2.98080679e-05 -1.19232271e-05  0.00000000e+00  0.00000000e+00
   1.98720452e-06  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.11458140e-04 -3.64583256e-04
   0.00000000e+00  6.07638760e-05]]
dPred/dW [[2.66775760e-07 1.34238331e-01 1.34246489e-01]]


Epoch 1000 loss: 0.160
dL/dPred [-0.46703003]
dPred/dH [[-0.26623441  0.28428836]]
dH/dW [[-0.27972869 -0.13986434  0.          0.          0.13986434  0.        ]
 [ 0.          0.         -0.2476091  -0.12380455  0.          0.12380455]]
dPred/dW [[0.03009342 0.15307577 0.17898575]]


dL/dPred [0.39644569]
dPred/dH [[-0.23617969  0.2535703 ]]
dH/dW [[7.50744131e-08 1.80178592e-08 0.00000000e+00 0.00000000e+00
  3.00297653e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.15263418e-05 2.76632202e-06
  0.00000000e+00 4.61053670e-07]]
dPred/dW [[1.58930547e-01 7.32755460e-08 1.58930548e-01]]


dL/dPred [0.39248545]
dPred/dH [[-0.23539169  0.25165727]]
dH/dW [[



dL/dPred [0.32551738]
dPred/dH [[-0.23433377  0.24879041]]
dH/dW [[7.11878075e-06 1.67500723e-06 0.00000000e+00 0.00000000e+00
  4.18751809e-07 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.94900245e-04 6.93882930e-05
  0.00000000e+00 1.73470733e-05]]
dPred/dW [[1.36268242e-01 2.36389718e-06 1.36268299e-01]]


dL/dPred [-0.25952828]
dPred/dH [[-0.19469308  0.20617236]]
dH/dW [[-7.68055218e-06 -3.07222087e-06  0.00000000e+00  0.00000000e+00
   5.12036812e-07  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.53281876e-04 -1.01312750e-04
   0.00000000e+00  1.68854584e-05]]
dPred/dW [[5.78219964e-08 1.12923503e-01 1.12925410e-01]]


Epoch 1000 loss: 0.107
dL/dPred [-0.38086557]
dPred/dH [[-0.26579909  0.28192266]]
dH/dW [[-0.24018829 -0.12009414  0.          0.          0.12009414  0.        ]
 [ 0.          0.         -0.21257645 -0.10628823  0.          0.10628823]]
dPred/dW [[0.02151809 0.13552819 0.15416814]]


dL/dPred [0.32571317]
dPred/dH [[-0.23494032  0.25001421]]
dH/dW 

dL/dPred [-0.22354628]
dPred/dH [[-0.18803016  0.1982199 ]]
dH/dW [[-3.00483520e-06 -1.20193408e-06  0.00000000e+00  0.00000000e+00
   2.00322347e-07  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.05006211e-04 -4.20024842e-05
   0.00000000e+00  7.00041404e-06]]
dPred/dW [[1.98879876e-08 9.92792102e-02 9.92799052e-02]]


Epoch 1000 loss: 0.079
dL/dPred [-0.3269288]
dPred/dH [[-0.25898451  0.27332289]]
dH/dW [[-0.21465681 -0.10732841  0.          0.          0.10732841  0.        ]
 [ 0.          0.         -0.19037096 -0.09518548  0.          0.09518548]]
dPred/dW [[0.01672118 0.12217576 0.13674379]]


dL/dPred [0.28115321]
dPred/dH [[-0.22874995  0.2419667 ]]
dH/dW [[2.59427479e-09 6.22625951e-10 0.00000000e+00 0.00000000e+00
  1.03770992e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.84535361e-07 1.16288487e-07
  0.00000000e+00 1.93814145e-08]]
dPred/dW [[1.20814822e-01 2.34156219e-09 1.20814822e-01]]


dL/dPred [0.27951912]
dPred/dH [[-0.22804502  0.24078907]]
dH/dW [[2

dH/dW [[9.03638275e-10 2.16873186e-10 0.00000000e+00 0.00000000e+00
  3.61455310e-11 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.80603325e-07 4.33447979e-08
  0.00000000e+00 7.22413299e-09]]
dPred/dW [[1.09175272e-01 7.88696690e-10 1.09175272e-01]]


dL/dPred [0.24828232]
dPred/dH [[-0.2208131   0.23222473]]
dH/dW [[1.32466684e-06 3.11686316e-07 0.00000000e+00 0.00000000e+00
  7.79215790e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.09865020e-05 1.43497652e-05
  0.00000000e+00 3.58744129e-06]]
dPred/dW [[1.08730125e-01 3.90064369e-07 1.08730133e-01]]


dL/dPred [-0.19768976]
dPred/dH [[-0.18113634  0.19024458]]
dH/dW [[-1.42920663e-06 -5.71682652e-07  0.00000000e+00  0.00000000e+00
   9.52804420e-08  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.23871890e-05 -2.09548756e-05
   0.00000000e+00  3.49247927e-06]]
dPred/dW [[8.48706525e-09 8.90742593e-02 8.90745704e-02]]


Epoch 1000 loss: 0.062
dL/dPred [-0.28753653]
dPred/dH [[-0.25032614  0.26313028]]
dH/dW [[-0.1956

dPred/dH [[-0.24237157  0.25403312]]
dH/dW [[-0.18252933 -0.09126467  0.          0.          0.09126467  0.        ]
 [ 0.          0.         -0.16269821 -0.08134911  0.          0.08134911]]
dPred/dW [[0.01150968 0.103181   0.11330214]]


dL/dPred [0.22571826]
dPred/dH [[-0.21414699  0.22475116]]
dH/dW [[3.89888122e-10 9.35731492e-11 0.00000000e+00 0.00000000e+00
  1.55955249e-11 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.23182042e-08 1.97563690e-08
  0.00000000e+00 3.29272817e-09]]
dPred/dW [[1.00121946e-01 3.29674352e-10 1.00121946e-01]]


dL/dPred [0.22481573]
dPred/dH [[-0.2136247   0.22396636]]
dH/dW [[7.52531516e-07 1.77066239e-07 0.00000000e+00 0.00000000e+00
  4.42665598e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.59484061e-05 8.45844850e-06
  0.00000000e+00 2.11461213e-06]]
dPred/dW [[9.97723318e-02 2.10980238e-07 9.97723362e-02]]


dL/dPred [-0.17940633]
dPred/dH [[-0.17501967  0.18330042]]
dH/dW [[-8.11919950e-07 -3.24767980e-07  0.00000000e+00  0.0000000

dH/dW [[-0.17131305 -0.08565653  0.          0.          0.08565653  0.        ]
 [ 0.          0.         -0.15307428 -0.07653714  0.          0.07653714]]
dPred/dW [[0.00990914 0.095993   0.10473997]]


dL/dPred [0.20650485]
dPred/dH [[-0.20704239  0.21668947]]
dH/dW [[1.90214511e-10 4.56514826e-11 0.00000000e+00 0.00000000e+00
  7.60858043e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.20979266e-08 1.01035024e-08
  0.00000000e+00 1.68391707e-09]]
dPred/dW [[9.25913623e-02 1.55916175e-10 9.25913623e-02]]


dL/dPred [0.20579836]
dPred/dH [[-0.20659184  0.2160332 ]]
dH/dW [[4.64345878e-07 1.09257854e-07 0.00000000e+00 0.00000000e+00
  2.73144634e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.28959173e-05 5.38727465e-06
  0.00000000e+00 1.34681866e-06]]
dPred/dW [[9.23109353e-02 1.24326261e-07 9.23109379e-02]]


dL/dPred [-0.16468267]
dPred/dH [[-0.16924957  0.17683426]]
dH/dW [[-5.00991320e-07 -2.00396528e-07  0.00000000e+00  0.00000000e+00
   3.33994214e-08  0.00000000e+

dPred/dW [[0.00870915 0.09003309 0.09774609]]


dL/dPred [0.19116497]
dPred/dH [[-0.20052258  0.20939418]]
dH/dW [[1.04249942e-10 2.50199861e-11 0.00000000e+00 0.00000000e+00
  4.16999768e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.40014479e-08 5.76034749e-09
  0.00000000e+00 9.60057915e-10]]
dPred/dW [[8.64464717e-02 8.29936195e-11 8.64464717e-02]]


dL/dPred [0.19059469]
dPred/dH [[-0.2001299   0.20883535]]
dH/dW [[3.09847319e-07 7.29052516e-08 0.00000000e+00 0.00000000e+00
  1.82263129e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.56890652e-05 3.69154476e-06
  0.00000000e+00 9.22886189e-07]]
dPred/dW [[8.62157600e-02 7.95674091e-08 8.62157616e-02]]


dL/dPred [-0.15294675]
dPred/dH [[-0.16405608  0.17107125]]
dH/dW [[-3.34300016e-07 -1.33720007e-07  0.00000000e+00  0.00000000e+00
   2.22866678e-08  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.34772667e-05 -5.39090668e-06
   0.00000000e+00  8.98484447e-07]]
dPred/dW [[1.57400040e-09 7.06251362e-02 7.06251997

dL/dPred [-0.20478882]
dPred/dH [[-0.21992556  0.22905378]]
dH/dW [[-0.15492257 -0.07746129  0.          0.          0.07746129  0.        ]
 [ 0.          0.         -0.13901792 -0.06950896  0.          0.06950896]]
dPred/dW [[0.00777761 0.08500207 0.0919098 ]]


dL/dPred [0.17859098]
dPred/dH [[-0.19457722  0.20280839]]
dH/dW [[6.23168184e-11 1.49560364e-11 0.00000000e+00 0.00000000e+00
  2.49267273e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.48389730e-08 3.56135351e-09
  0.00000000e+00 5.93558919e-10]]
dPred/dW [[8.13218040e-02 4.82692821e-11 8.13218040e-02]]


dL/dPred [0.17811939]
dPred/dH [[-0.19423149  0.20232522]]
dH/dW [[2.19189421e-07 5.15739813e-08 0.00000000e+00 0.00000000e+00
  1.28934953e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.13529593e-05 2.67128454e-06
  0.00000000e+00 6.67821135e-07]]
dPred/dW [[8.11280642e-02 5.41790728e-08 8.11280653e-02]]


dL/dPred [-0.14332673]
dPred/dH [[-0.15937245  0.16591345]]
dH/dW [[-2.36487541e-07 -9.45950164e-08  0.

dL/dPred [-0.19241791]
dPred/dH [[-0.21370026  0.22224443]]
dH/dW [[-0.14870323 -0.07435161  0.          0.          0.07435161  0.        ]
 [ 0.          0.         -0.13368152 -0.06684076  0.          0.06684076]]
dPred/dW [[0.00703411 0.08068968 0.08695279]]


dL/dPred [0.1680645]
dPred/dH [[-0.1891576   0.19685084]]
dH/dW [[3.98292510e-11 9.55902024e-12 0.00000000e+00 0.00000000e+00
  1.59317004e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.76434326e-09 2.34344238e-09
  0.00000000e+00 3.90573731e-10]]
dPred/dW [[7.69708325e-02 3.00627852e-11 7.69708325e-02]]


dL/dPred [0.16766685]
dPred/dH [[-0.18885036  0.19642771]]
dH/dW [[1.62188560e-07 3.81620141e-08 0.00000000e+00 0.00000000e+00
  9.54050352e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.56709672e-06 2.01578746e-06
  0.00000000e+00 5.03946866e-07]]
dPred/dW [[7.68053826e-02 3.87058517e-08 7.68053833e-02]]


dL/dPred [-0.13526567]
dPred/dH [[-0.15513083  0.16127076]]
dH/dW [[-1.74988261e-07 -6.99953045e-08  0.0

dL/dPred [0.1590991]
dPred/dH [[-0.18420617  0.19144091]]
dH/dW [[2.68340905e-11 6.44018172e-12 0.00000000e+00 0.00000000e+00
  1.07336362e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.74927718e-09 1.61982652e-09
  0.00000000e+00 2.69971087e-10]]
dPred/dW [[7.32214208e-02 1.97676666e-11 7.32214208e-02]]


dL/dPred [0.15875839]
dPred/dH [[-0.18393085  0.1910663 ]]
dH/dW [[1.24349932e-07 2.92588076e-08 0.00000000e+00 0.00000000e+00
  7.31470190e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.68248218e-06 1.57234875e-06
  0.00000000e+00 3.93087187e-07]]
dPred/dW [[7.30781399e-02 2.87260920e-08 7.30781405e-02]]


dL/dPred [-0.12839018]
dPred/dH [[-0.15127054  0.15706656]]
dH/dW [[-1.34163463e-07 -5.36653854e-08  0.00000000e+00  0.00000000e+00
   8.94423090e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.74044462e-06 -2.29617785e-06
   0.00000000e+00  3.82696308e-07]]
dPred/dW [[5.37316442e-10 6.00740565e-02 6.00740795e-02]]


Epoch 1000 loss: 0.025
dL/dPred [-0.1815

dH/dW [[-0.13877111 -0.06938556  0.          0.          0.06938556  0.        ]
 [ 0.          0.         -0.12515064 -0.06257532  0.          0.06257532]]
dPred/dW [[0.00592235 0.07365596 0.07895158]]


dL/dPred [0.15135338]
dPred/dH [[-0.17966745  0.18650639]]
dH/dW [[1.88682403e-11 4.52837767e-12 0.00000000e+00 0.00000000e+00
  7.54729612e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.85416740e-09 1.16500017e-09
  0.00000000e+00 1.94166696e-10]]
dPred/dW [[6.99497290e-02 1.35819078e-11 6.99497290e-02]]


dL/dPred [0.15105754]
dPred/dH [[-0.17941888  0.18617163]]
dH/dW [[9.81106517e-08 2.30848592e-08 0.00000000e+00 0.00000000e+00
  5.77121481e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.35355108e-06 1.25965908e-06
  0.00000000e+00 3.14914770e-07]]
dPred/dW [[6.98241743e-02 2.19886708e-08 6.98241747e-02]]


dL/dPred [-0.12243988]
dPred/dH [[-0.14773974  0.15323729]]
dH/dW [[-1.05853419e-07 -4.23413675e-08  0.00000000e+00  0.00000000e+00
   7.05689458e-09  0.00000000e+

dL/dPred [0.14458041]
dPred/dH [[-0.17549155  0.18198504]]
dH/dW [[1.37390099e-11 3.29736238e-12 0.00000000e+00 0.00000000e+00
  5.49560397e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.60691689e-09 8.65660055e-10
  0.00000000e+00 1.44276676e-10]]
dPred/dW [[6.70643325e-02 9.67581896e-12 6.70643325e-02]]


dL/dPred [0.14432062]
dPred/dH [[-0.17526565  0.18168346]]
dH/dW [[7.92519369e-08 1.86475146e-08 0.00000000e+00 0.00000000e+00
  4.66187864e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.38404023e-06 1.03153888e-06
  0.00000000e+00 2.57884719e-07]]
dPred/dW [[6.69531978e-02 1.72662112e-08 6.69531981e-02]]


dL/dPred [-0.11722726]
dPred/dH [[-0.14449483  0.14973061]]
dH/dW [[-8.55063996e-08 -3.42025598e-08  0.00000000e+00  0.00000000e+00
   5.70042664e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.76602387e-06 -1.50640955e-06
   0.00000000e+00  2.51068258e-07]]
dPred/dW [[3.14538561e-10 5.51780596e-02 5.51780734e-02]]


Epoch 1000 loss: 0.021
dL/dPred [-0.164

  0.00000000e+00 1.10162126e-10]]
dPred/dW [[6.44962096e-02 7.10503955e-12 6.44962096e-02]]


dL/dPred [0.13836662]
dPred/dH [[-0.17142847  0.17755044]]
dH/dW [[6.52875962e-08 1.53617873e-08 0.00000000e+00 0.00000000e+00
  3.84044683e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.65641296e-06 8.60332462e-07
  0.00000000e+00 2.15083115e-07]]
dPred/dW [[6.43969810e-02 1.38507063e-08 6.43969812e-02]]


dL/dPred [-0.11261354]
dPred/dH [[-0.14149928  0.1465034 ]]
dH/dW [[-7.04400100e-08 -2.81760040e-08  0.00000000e+00  0.00000000e+00
   4.69600066e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.14097186e-06 -1.25638874e-06
   0.00000000e+00  2.09398124e-07]]
dPred/dW [[2.49528186e-10 5.31363069e-02 5.31363181e-02]]


Epoch 1000 loss: 0.019
dL/dPred [-0.15768347]
dPred/dH [[-0.19339854  0.20028154]]
dH/dW [[-0.13099203 -0.06549602  0.          0.          0.06549602  0.        ]
 [ 0.          0.         -0.11845776 -0.05922888  0.          0.05922888]]
dPred/dW [[0.00511726

dPred/dH [[-0.16819824  0.174127  ]]
dH/dW [[7.99360578e-12 1.91846539e-12 0.00000000e+00 0.00000000e+00
  3.19744231e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.17224874e-09 5.21339697e-10
  0.00000000e+00 8.68899495e-11]]
dPred/dW [[6.22798663e-02 5.41149443e-12 6.22798663e-02]]


dL/dPred [0.13325951]
dPred/dH [[-0.16800785  0.17387639]]
dH/dW [[5.50569935e-08 1.29545867e-08 0.00000000e+00 0.00000000e+00
  3.23864667e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.11689457e-06 7.33386958e-07
  0.00000000e+00 1.83346740e-07]]
dPred/dW [[6.21902294e-02 1.14023779e-08 6.21902296e-02]]


dL/dPred [-0.10865003]
dPred/dH [[-0.1388297   0.14363497]]
dH/dW [[-5.94020215e-08 -2.37608086e-08  0.00000000e+00  0.00000000e+00
   3.96013477e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.67751012e-06 -1.07100405e-06
   0.00000000e+00  1.78500675e-07]]
dPred/dW [[2.03447202e-10 5.13737984e-02 5.13738076e-02]]


Epoch 1000 loss: 0.018
dL/dPred [-0.15173225]
dPred/dH [[-0.1

dL/dPred [-0.10506936]
dPred/dH [[-0.13633881  0.1409647 ]]
dH/dW [[-5.07567873e-08 -2.03027149e-08  0.00000000e+00  0.00000000e+00
   3.38378582e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.31059083e-06 -9.24236333e-07
   0.00000000e+00  1.54039389e-07]]
dPred/dW [[1.68427215e-10 4.97747781e-02 4.97747858e-02]]


Epoch 1000 loss: 0.016
dL/dPred [-0.14637017]
dPred/dH [[-0.18579144  0.19213069]]
dH/dW [[-0.12512336 -0.06256168  0.          0.          0.06256168  0.        ]
 [ 0.          0.         -0.11339977 -0.05669988  0.          0.05669988]]
dPred/dW [[0.00454851 0.06373616 0.06782903]]


dL/dPred [0.12865665]
dPred/dH [[-0.16486379  0.17054928]]
dH/dW [[6.26720897e-12 1.50413015e-12 0.00000000e+00 0.00000000e+00
  2.50688359e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.72963053e-09 4.15111328e-10
  0.00000000e+00 6.91852213e-11]]
dPred/dW [[6.01901923e-02 4.16427177e-12 6.01901923e-02]]


dL/dPred [0.12847039]
dPred/dH [[-0.16468804  0.17031932]]
dH/dW [[

dL/dPred [0.12430513]
dPred/dH [[-0.16170959  0.16713494]]
dH/dW [[4.04217159e-08 9.51099197e-09 0.00000000e+00 0.00000000e+00
  2.37774799e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.33316950e-06 5.48981058e-07
  0.00000000e+00 1.37245265e-07]]
dPred/dW [[5.82896230e-02 7.99997585e-09 5.82896232e-02]]


dL/dPred [-0.10168506]
dPred/dH [[-0.13391319  0.13836983]]
dH/dW [[-4.36117461e-08 -1.74446984e-08  0.00000000e+00  0.00000000e+00
   2.90744974e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.00426712e-06 -8.01706848e-07
   0.00000000e+00  1.33617808e-07]]
dPred/dW [[1.40306448e-10 4.82575596e-02 4.82575660e-02]]


Epoch 1000 loss: 0.015
dL/dPred [-0.14131537]
dPred/dH [[-0.18221875  0.18831522]]
dH/dW [[-0.1224814  -0.0612407   0.          0.          0.0612407   0.        ]
 [ 0.          0.         -0.11111985 -0.05555992  0.          0.05555992]]
dPred/dW [[0.00430341 0.06178788 0.06566518]]


dL/dPred [0.12430862]
dPred/dH [[-0.16175252  0.16721882]]
dH/dW [[

dL/dPred [0.12050564]
dPred/dH [[-0.15895353  0.16422874]]
dH/dW [[4.09672296e-12 9.83213511e-13 0.00000000e+00 0.00000000e+00
  1.63868918e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.16044325e-09 2.78506381e-10
  0.00000000e+00 4.64177301e-11]]
dPred/dW [[5.66224164e-02 2.62828404e-12 5.66224164e-02]]


dL/dPred [0.12035123]
dPred/dH [[-0.15880149  0.16403179]]
dH/dW [[3.51081925e-08 8.26075118e-09 0.00000000e+00 0.00000000e+00
  2.06518779e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.04431653e-06 4.81015653e-07
  0.00000000e+00 1.20253913e-07]]
dPred/dW [[5.65545097e-02 6.80090194e-09 5.65545098e-02]]


dL/dPred [-0.0986024]
dPred/dH [[-0.13164157  0.13594437]]
dH/dW [[-3.78788882e-08 -1.51515553e-08  0.00000000e+00  0.00000000e+00
   2.52525921e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.75613365e-06 -7.02453462e-07
   0.00000000e+00  1.17075577e-07]]
dPred/dW [[1.18360398e-10 4.68705879e-02 4.68705934e-02]]


Epoch 1000 loss: 0.014
dL/dPred [-0.1367

dPred/dH [[-0.1561777  0.1612369]]
dH/dW [[3.09402705e-08 7.28006365e-09 0.00000000e+00 0.00000000e+00
  1.82001591e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.81576619e-06 4.27239104e-07
  0.00000000e+00 1.06809776e-07]]
dPred/dW [[5.50224514e-02 5.87693635e-09 5.50224515e-02]]


dL/dPred [-0.09588794]
dPred/dH [[-0.12959074  0.13375839]]
dH/dW [[-3.33820380e-08 -1.33528152e-08  0.00000000e+00  0.00000000e+00
   2.22546920e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.55980190e-06 -6.23920760e-07
   0.00000000e+00  1.03986793e-07]]
dPred/dW [[1.01582314e-10 4.56453421e-02 4.56453469e-02]]


Epoch 1000 loss: 0.014
dL/dPred [-0.13268853]
dPred/dH [[-0.17586022  0.18154301]]
dH/dW [[-0.11794045 -0.05897022  0.          0.          0.05897022  0.        ]
 [ 0.          0.         -0.10719641 -0.05359821  0.          0.05359821]]
dPred/dW [[0.00389808 0.05842265 0.0619427 ]]


dL/dPred [0.11687749]
dPred/dH [[-0.15621366  0.16130718]]
dH/dW [[3.36952688e-12 8.0868645

dL/dPred [-0.09338253]
dPred/dH [[-0.12765473  0.13169793]]
dH/dW [[-2.96477923e-08 -1.18591169e-08  0.00000000e+00  0.00000000e+00
   1.97651949e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.39546996e-06 -5.58187984e-07
   0.00000000e+00  9.30313306e-08]]
dPred/dW [[8.79772364e-11 4.45111868e-02 4.45111910e-02]]


Epoch 1000 loss: 0.013
dL/dPred [-0.12897327]
dPred/dH [[-0.17301646  0.17852147]]
dH/dW [[-0.11597121 -0.05798561  0.          0.          0.05798561  0.        ]
 [ 0.          0.         -0.10549295 -0.05274648  0.          0.05274648]]
dPred/dW [[0.00372861 0.05695772 0.06032811]]


dL/dPred [0.11367303]
dPred/dH [[-0.15373574  0.15866932]]
dH/dW [[2.82551760e-12 6.78124223e-13 0.00000000e+00 0.00000000e+00
  1.13020704e-13 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.19061006e-10 1.96574642e-10
  0.00000000e+00 3.27624403e-11]]
dPred/dW [[5.36061250e-02 1.75626747e-12 5.36061250e-02]]


dL/dPred [0.11354247]
dPred/dH [[-0.15360243  0.15849805]]
dH/dW [[


dL/dPred [-0.09096783]
dPred/dH [[-0.12574867  0.12967221]]
dH/dW [[-2.63946560e-08 -1.05578624e-08  0.00000000e+00  0.00000000e+00
   1.75964373e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.25122492e-06 -5.00489968e-07
   0.00000000e+00  8.34149947e-08]]
dPred/dW [[7.63951628e-11 4.34151271e-02 4.34151307e-02]]


Epoch 1000 loss: 0.012
dL/dPred [-0.12540039]
dPred/dH [[-0.17021965  0.17555396]]
dH/dW [[-0.11406903 -0.05703452  0.          0.          0.05703452  0.        ]
 [ 0.          0.         -0.10384626 -0.05192313  0.          0.05192313]]
dPred/dW [[0.00356854 0.05554002 0.05876888]]


dL/dPred [0.11058897]
dPred/dH [[-0.15129823  0.15607838]]
dH/dW [[2.37587727e-12 5.70210545e-13 0.00000000e+00 0.00000000e+00
  9.50350909e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.96705720e-10 1.67209373e-10
  0.00000000e+00 2.78682288e-11]]
dPred/dW [[5.22370049e-02 1.45575281e-12 5.22370049e-02]]


dL/dPred [0.11046835]
dPred/dH [[-0.151173   0.1559181]]
dH/dW [[2

 [ 0.          0.         -0.10231467 -0.05115733  0.          0.05115733]]
dPred/dW [[0.00342298 0.05422041 0.05732043]]


dL/dPred [0.10773314]
dPred/dH [[-0.14899388  0.15363243]]
dH/dW [[2.02060590e-12 4.84945417e-13 0.00000000e+00 0.00000000e+00
  8.08242362e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.98152849e-10 1.43556684e-10
  0.00000000e+00 2.39261139e-11]]
dPred/dW [[5.09649645e-02 1.21939355e-12 5.09649645e-02]]


dL/dPred [0.10762129]
dPred/dH [[-0.14887594  0.153482  ]]
dH/dW [[2.18333793e-08 5.13726572e-09 0.00000000e+00 0.00000000e+00
  1.28431643e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.30896893e-06 3.07992690e-07
  0.00000000e+00 7.69981726e-08]]
dPred/dW [[5.09150600e-02 3.92036689e-09 5.09150601e-02]]


dL/dPred [-0.08864248]
dPred/dH [[-0.12387495  0.12768358]]
dH/dW [[-2.35564440e-08 -9.42257758e-09  0.00000000e+00  0.00000000e+00
   1.57042960e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.12444720e-06 -4.49778881e-07
   0.000000

dL/dPred [0.10497512]
dPred/dH [[-0.14669942  0.15117659]]
dH/dW [[1.96916268e-08 4.63332394e-09 0.00000000e+00 0.00000000e+00
  1.15833099e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.18797642e-06 2.79523864e-07
  0.00000000e+00 6.98809659e-08]]
dPred/dW [[4.97326156e-02 3.47536346e-09 4.97326156e-02]]


dL/dPred [-0.08656464]
dPred/dH [[-0.12216824  0.12587445]]
dH/dW [[-2.12456659e-08 -8.49826634e-09  0.00000000e+00  0.00000000e+00
   1.41637772e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.02051079e-06 -4.08204317e-07
   0.00000000e+00  6.80340529e-08]]
dPred/dW [[5.86507327e-11 4.14089601e-02 4.14089629e-02]]


Epoch 1000 loss: 0.011
dL/dPred [-0.11890593]
dPred/dH [[-0.16497495  0.16999983]]
dH/dW [[-0.11058859 -0.0552943   0.          0.          0.0552943   0.        ]
 [ 0.          0.         -0.10082995 -0.05041497  0.          0.05041497]]
dPred/dW [[0.00328494 0.05294063 0.05591831]]


dL/dPred [0.10497692]
dPred/dH [[-0.14672582  0.15122817]]
dH/dW [[

dL/dPred [0.10250766]
dPred/dH [[-0.14463303  0.14899033]]
dH/dW [[1.78566828e-08 4.20157242e-09 0.00000000e+00 0.00000000e+00
  1.05039310e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.08365126e-06 2.54976767e-07
  0.00000000e+00 6.37441917e-08]]
dPred/dW [[4.86268764e-02 3.09968113e-09 4.86268764e-02]]


dL/dPred [-0.0846246]
dPred/dH [[-0.12054645  0.12415729]]
dH/dW [[-1.92659107e-08 -7.70636426e-09  0.00000000e+00  0.00000000e+00
   1.28439404e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.30892147e-07 -3.72356859e-07
   0.00000000e+00  6.20594765e-08]]
dPred/dW [[5.20461748e-11 4.05219658e-02 4.05219683e-02]]


Epoch 1000 loss: 0.010
dL/dPred [-0.11605327]
dPred/dH [[-0.16260351  0.16749287]]
dH/dW [[-0.10904981 -0.05452491  0.          0.          0.05452491  0.        ]
 [ 0.          0.         -0.09949492 -0.04974746  0.          0.04974746]]
dPred/dW [[0.00316339 0.05178969 0.05465955]]


dL/dPred [0.1025093]
dPred/dH [[-0.14465767  0.14903848]]
dH/dW [[1.

dL/dPred [0.10029095]
dPred/dH [[-0.1427675   0.14703938]]
dH/dW [[1.30451205e-12 3.13082893e-13 0.00000000e+00 0.00000000e+00
  5.21804822e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.96730706e-10 9.52153695e-11
  0.00000000e+00 1.58692282e-11]]
dPred/dW [[4.76309084e-02 7.55865757e-13 4.76309084e-02]]


dL/dPred [0.1002]
dPred/dH [[-0.14266758  0.14691306]]
dH/dW [[1.62727225e-08 3.82887588e-09 0.00000000e+00 0.00000000e+00
  9.57218970e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.93049875e-07 2.33658794e-07
  0.00000000e+00 5.84146985e-08]]
dPred/dW [[4.75899895e-02 2.77995505e-09 4.75899895e-02]]


dL/dPred [-0.08280789]
dPred/dH [[-0.11900251  0.12252427]]
dH/dW [[-1.75569472e-08 -7.02277887e-09  0.00000000e+00  0.00000000e+00
   1.17046314e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.53062650e-07 -3.41225060e-07
   0.00000000e+00  5.68708434e-08]]
dPred/dW [[4.64552802e-11 3.96896542e-02 3.96896565e-02]]


Epoch 1000 loss: 0.010
dL/dPred [-0.1133870

 [ 0.          0.         -0.09710642 -0.04855321  0.          0.04855321]]
dPred/dW [[0.00295201 0.04973103 0.0524131 ]]


dL/dPred [0.09812124]
dPred/dH [[-0.14088984  0.1450555 ]]
dH/dW [[1.14352972e-12 2.74447132e-13 0.00000000e+00 0.00000000e+00
  4.57411886e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.50622359e-10 8.41493662e-11
  0.00000000e+00 1.40248944e-11]]
dPred/dW [[4.66536758e-02 6.54312874e-13 4.66536758e-02]]


dL/dPred [0.09803586]
dPred/dH [[-0.14079491  0.14493579]]
dH/dW [[1.48960002e-08 3.50494122e-09 0.00000000e+00 0.00000000e+00
  8.76235306e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.13850316e-07 2.15023604e-07
  0.00000000e+00 5.37559009e-08]]
dPred/dW [[4.66151746e-02 2.50584084e-09 4.66151746e-02]]


dL/dPred [-0.08110208]
dPred/dH [[-0.11753013  0.12096847]]
dH/dW [[-1.60715764e-08 -6.42863055e-09  0.00000000e+00  0.00000000e+00
   1.07143842e-09  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.85027677e-07 -3.14011071e-07
   0.000000

dL/dPred [-0.07955884]
dPred/dH [[-0.11617878  0.11954184]]
dH/dW [[-1.48211941e-08 -5.92847765e-09  0.00000000e+00  0.00000000e+00
   9.88079608e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.27449750e-07 -2.90979900e-07
   0.00000000e+00  4.84966500e-08]]
dPred/dW [[3.77416953e-11 3.81970168e-02 3.81970187e-02]]


Epoch 1000 loss: 0.009
dL/dPred [-0.10863119]
dPred/dH [[-0.15623132  0.16076941]]
dH/dW [[-0.10501452 -0.05250726  0.          0.          0.05250726  0.        ]
 [ 0.          0.         -0.09598944 -0.04799472  0.          0.04799472]]
dPred/dW [[0.00285584 0.04876889 0.05136541]]


dL/dPred [0.09608154]
dPred/dH [[-0.1390981   0.14316421]]
dH/dW [[1.01030295e-12 2.42472709e-13 0.00000000e+00 0.00000000e+00
  4.04121181e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.11645946e-10 7.47950270e-11
  0.00000000e+00 1.24658378e-11]]
dPred/dW [[4.57328538e-02 5.70098340e-13 4.57328538e-02]]


dL/dPred [0.0960012]
dPred/dH [[-0.13900775  0.14305054]]
dH/dW [[1

dPred/dW [[3.41792564e-11 3.74976713e-02 3.74976730e-02]]


Epoch 1000 loss: 0.009
dL/dPred [-0.10641437]
dPred/dH [[-0.15426953  0.15870312]]
dH/dW [[-0.10379969 -0.05189984  0.          0.          0.05189984  0.        ]
 [ 0.          0.         -0.09493278 -0.04746639  0.          0.04746639]]
dPred/dW [[0.00276644 0.04785925 0.05037618]]


dL/dPred [0.09415956]
dPred/dH [[-0.13738576  0.14135833]]
dH/dW [[8.93729535e-13 2.14495088e-13 0.00000000e+00 0.00000000e+00
  3.57491814e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.78456860e-10 6.68296465e-11
  0.00000000e+00 1.11382744e-11]]
dPred/dW [[4.48632742e-02 4.99699459e-13 4.48632742e-02]]


dL/dPred [0.0940838]
dPred/dH [[-0.13729961  0.1412502 ]]
dH/dW [[1.26325683e-08 2.97236902e-09 0.00000000e+00 0.00000000e+00
  7.43092254e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.82613593e-07 1.84144375e-07
  0.00000000e+00 4.60360937e-08]]
dPred/dW [[4.48289576e-02 2.06375019e-09 4.48289576e-02]]


dL/dPred [-0.07798155

dL/dPred [0.09234347]
dPred/dH [[-0.13572872  0.13959584]]
dH/dW [[1.17310956e-08 2.76025780e-09 0.00000000e+00 0.00000000e+00
  6.90064450e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.29947345e-07 1.71752316e-07
  0.00000000e+00 4.29380791e-08]]
dPred/dW [[4.40399061e-02 1.89098906e-09 4.40399062e-02]]


dL/dPred [-0.07660509]
dPred/dH [[-0.11353997  0.11675948]]
dH/dW [[-1.26568986e-08 -5.06275945e-09  0.00000000e+00  0.00000000e+00
   8.43793242e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.27049056e-07 -2.50819623e-07
   0.00000000e+00  4.18032704e-08]]
dPred/dW [[3.10815110e-11 3.68354569e-02 3.68354585e-02]]


Epoch 1000 loss: 0.008
dL/dPred [-0.10432202]
dPred/dH [[-0.15239238  0.15672753]]
dH/dW [[-0.10264872 -0.05132436  0.          0.          0.05132436  0.        ]
 [ 0.          0.         -0.09393107 -0.04696553  0.          0.04696553]]
dPred/dW [[0.0026831  0.04699757 0.04944024]]


dL/dPred [0.09234457]
dPred/dH [[-0.13574693  0.13963143]]
dH/dW [[

dH/dW [[7.21644966e-13 1.73194792e-13 0.00000000e+00 0.00000000e+00
  2.88657986e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.26377683e-10 5.43306438e-11
  0.00000000e+00 9.05510731e-12]]
dPred/dW [[4.32906787e-02 3.92001741e-13 4.32906787e-02]]


dL/dPred [0.09062611]
dPred/dH [[-0.13415913  0.13794405]]
dH/dW [[1.08946092e-08 2.56343746e-09 0.00000000e+00 0.00000000e+00
  6.40859365e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.80852206e-07 1.60200519e-07
  0.00000000e+00 4.00501298e-08]]
dPred/dW [[4.32597830e-02 1.73255999e-09 4.32597830e-02]]


dL/dPred [-0.07524535]
dPred/dH [[-0.11230158  0.11545526]]
dH/dW [[-1.17543979e-08 -4.70175916e-09  0.00000000e+00  0.00000000e+00
   7.83626527e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.84874729e-07 -2.33949892e-07
   0.00000000e+00  3.89916486e-08]]
dPred/dW [[2.83729314e-11 3.62072101e-02 3.62072115e-02]]


Epoch 1000 loss: 0.008
dL/dPred [-0.1023431]
dPred/dH [[-0.15059378  0.15483603]]
dH/dW [[-0.10155

dL/dPred [0.08906245]
dPred/dH [[-0.13272843  0.13645431]]
dH/dW [[6.49480469e-13 1.55875313e-13 0.00000000e+00 0.00000000e+00
  2.59792188e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.04965571e-10 4.91917371e-11
  0.00000000e+00 8.19862286e-12]]
dPred/dW [[4.25481962e-02 3.48836614e-13 4.25481962e-02]]


dL/dPred [0.08899799]
dPred/dH [[-0.13265295  0.13636015]]
dH/dW [[1.01479054e-08 2.38774245e-09 0.00000000e+00 0.00000000e+00
  5.96935612e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.36829035e-07 1.49842126e-07
  0.00000000e+00 3.74605315e-08]]
dPred/dW [[4.25188352e-02 1.59277822e-09 4.25188352e-02]]


dL/dPred [-0.07395493]
dPred/dH [[-0.11111222  0.11420357]]
dH/dW [[-1.09487676e-08 -4.37950705e-09  0.00000000e+00  0.00000000e+00
   7.29917841e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.47057383e-07 -2.18822953e-07
   0.00000000e+00  3.64704922e-08]]
dPred/dW [[2.59924709e-11 3.56101310e-02 3.56101323e-02]]


Epoch 1000 loss: 0.008
dL/dPred [-0.100

dL/dPred [-0.09875726]
dPred/dH [[-0.14727593  0.15135029]]
dH/dW [[-0.09956573 -0.04978287  0.          0.          0.04978287  0.        ]
 [ 0.          0.         -0.09124492 -0.04562246  0.          0.04562246]]
dPred/dW [[0.00246642 0.04469106 0.04694038]]


dL/dPred [0.087513]
dPred/dH [[-0.13127828  0.13492958]]
dH/dW [[5.82867088e-13 1.39888101e-13 0.00000000e+00 0.00000000e+00
  2.33146835e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.86292874e-10 4.47102898e-11
  0.00000000e+00 7.45171497e-12]]
dPred/dW [[4.18418697e-02 3.11793687e-13 4.18418697e-02]]


dL/dPred [0.08745175]
dPred/dH [[-0.13120591  0.13483946]]
dH/dW [[9.47851619e-09 2.23023910e-09 0.00000000e+00 0.00000000e+00
  5.57559776e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.97193378e-07 1.40516089e-07
  0.00000000e+00 3.51290223e-08]]
dPred/dW [[4.18139216e-02 1.46888223e-09 4.18139216e-02]]


dL/dPred [-0.07272816]
dPred/dH [[-0.1099686   0.11300084]]
dH/dW [[-1.02265481e-08 -4.09061924e-09  0.00

dL/dPred [0.08603914]
dPred/dH [[-0.12988359  0.13346414]]
dH/dW [[5.32907052e-13 1.27897692e-13 0.00000000e+00 0.00000000e+00
  2.13162821e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.69927577e-10 4.07826186e-11
  0.00000000e+00 6.79710309e-12]]
dPred/dW [[4.11688846e-02 2.79829153e-13 4.11688846e-02]]


dL/dPred [0.08598083]
dPred/dH [[-0.12981411  0.13337776]]
dH/dW [[8.87604967e-09 2.08848227e-09 0.00000000e+00 0.00000000e+00
  5.22120569e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.61372823e-07 1.32087723e-07
  0.00000000e+00 3.30219308e-08]]
dPred/dW [[4.11422406e-02 1.35859627e-09 4.11422407e-02]]


dL/dPred [-0.07156001]
dPred/dH [[-0.10886773  0.11184382]]
dH/dW [[-9.57653603e-09 -3.83061441e-09  0.00000000e+00  0.00000000e+00
   6.38435735e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.82238022e-07 -1.92895209e-07
   0.00000000e+00  3.21492015e-08]]
dPred/dW [[2.20259022e-11 3.44997943e-02 3.44997954e-02]]


Epoch 1000 loss: 0.007
dL/dPred [-0.096

dL/dPred [-0.09544613]
dPred/dH [[-0.1441432   0.14806313]]
dH/dW [[-0.09771505 -0.04885753  0.          0.          0.04885753  0.        ]
 [ 0.          0.         -0.08963031 -0.04481515  0.          0.04481515]]
dPred/dW [[0.00234094 0.04330842 0.04544557]]


dL/dPred [0.08463498]
dPred/dH [[-0.1285408  0.1320541]]
dH/dW [[4.82947016e-13 1.15907284e-13 0.00000000e+00 0.00000000e+00
  1.93178806e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.55517538e-10 3.73242092e-11
  0.00000000e+00 6.22070153e-12]]
dPred/dW [[4.05267219e-02 2.52104641e-13 4.05267219e-02]]


dL/dPred [0.08457941]
dPred/dH [[-0.12847401  0.13197122]]
dH/dW [[8.33180879e-09 1.96042560e-09 0.00000000e+00 0.00000000e+00
  4.90106400e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.28885690e-07 1.24443692e-07
  0.00000000e+00 3.11109229e-08]]
dPred/dW [[4.05012847e-02 1.26003239e-09 4.05012848e-02]]


dL/dPred [-0.07044598]
dPred/dH [[-0.1078069   0.11072957]]
dH/dW [[-8.98934658e-09 -3.59573863e-09  0.00

dL/dPred [0.08329455]
dPred/dH [[-0.12723316  0.13066958]]
dH/dW [[7.85730658e-09 1.84877802e-09 0.00000000e+00 0.00000000e+00
  4.62194505e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00455108e-07 1.17754143e-07
  0.00000000e+00 2.94385358e-08]]
dPred/dW [[3.99127806e-02 1.17497385e-09 3.99127806e-02]]


dL/dPred [-0.0694237]
dPred/dH [[-0.10682388  0.10969762]]
dH/dW [[-8.47739551e-09 -3.39095820e-09  0.00000000e+00  0.00000000e+00
   5.65159701e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.29907699e-07 -1.71963080e-07
   0.00000000e+00  2.86605133e-08]]
dPred/dW [[1.89367695e-11 3.35069342e-02 3.35069351e-02]]


Epoch 1000 loss: 0.007
dL/dPred [-0.09390577]
dPred/dH [[-0.14266265  0.14651093]]
dH/dW [[-0.09684967 -0.04842483  0.          0.          0.04842483  0.        ]
 [ 0.          0.         -0.08887474 -0.04443737  0.          0.04443737]]
dPred/dW [[0.00228345 0.0426626  0.04474831]]


dL/dPred [0.08329529]
dPred/dH [[-0.12724666  0.13069597]]
dH/dW [[4

dL/dPred [0.08211564]
dPred/dH [[-0.12609646  0.12948955]]
dH/dW [[4.05231404e-13 9.72555370e-14 0.00000000e+00 0.00000000e+00
  1.62092562e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.32314986e-10 3.17555967e-11
  0.00000000e+00 5.29259946e-12]]
dPred/dW [[3.93720756e-02 2.08380626e-13 3.93720756e-02]]


dL/dPred [0.08206475]
dPred/dH [[-0.12603438  0.12941273]]
dH/dW [[7.42419081e-09 1.74686843e-09 0.00000000e+00 0.00000000e+00
  4.36717107e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.74412711e-07 1.11626520e-07
  0.00000000e+00 2.79066301e-08]]
dPred/dW [[3.93487173e-02 1.09809013e-09 3.93487173e-02]]


dL/dPred [-0.06844436]
dPred/dH [[-0.10587347  0.10870045]]
dH/dW [[-8.01009941e-09 -3.20403976e-09  0.00000000e+00  0.00000000e+00
   5.34006627e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.07536419e-07 -1.63014567e-07
   0.00000000e+00  2.71690946e-08]]
dPred/dW [[1.76494656e-11 3.30510226e-02 3.30510235e-02]]


Epoch 1000 loss: 0.007
dL/dPred [-0.092

dL/dPred [-0.09113815]
dPred/dH [[-0.13996459  0.14368449]]
dH/dW [[-0.09528734 -0.04764367  0.          0.          0.04764367  0.        ]
 [ 0.          0.         -0.08750971 -0.04375485  0.          0.04375485]]
dPred/dW [[0.00218157 0.04149806 0.04349253]]


dL/dPred [0.08088688]
dPred/dH [[-0.12488763  0.1282223 ]]
dH/dW [[3.71924713e-13 8.92619312e-14 0.00000000e+00 0.00000000e+00
  1.48769885e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.22135668e-10 2.93125603e-11
  0.00000000e+00 4.88542671e-12]]
dPred/dW [[3.88077679e-02 1.89592506e-13 3.88077679e-02]]


dL/dPred [0.08083817]
dPred/dH [[-0.12482778  0.12814834]]
dH/dW [[7.01195324e-09 1.64987135e-09 0.00000000e+00 0.00000000e+00
  4.12467837e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.49539571e-07 1.05774017e-07
  0.00000000e+00 2.64435042e-08]]
dPred/dW [[3.87853838e-02 1.02562149e-09 3.87853838e-02]]


dL/dPred [-0.06746677]
dPred/dH [[-0.10491615  0.10769655]]
dH/dW [[-7.56532978e-09 -3.02613191e-09  0.

dPred/dH [[-0.10406325  0.10680259]]
dH/dW [[-7.18979039e-09 -2.87591615e-09  0.00000000e+00  0.00000000e+00
   4.79319359e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.68069148e-07 -1.47227659e-07
   0.00000000e+00  2.45379432e-08]]
dPred/dW [[1.54305368e-11 3.21926001e-02 3.21926009e-02]]


Epoch 1000 loss: 0.006
dL/dPred [-0.08983949]
dPred/dH [[-0.13868147  0.14234129]]
dH/dW [[-0.09455081 -0.0472754   0.          0.          0.0472754   0.        ]
 [ 0.          0.         -0.08686575 -0.04343288  0.          0.04343288]]
dPred/dW [[0.00213439 0.04094977 0.04290196]]


dL/dPred [0.07975617]
dPred/dH [[-0.12376545  0.12704647]]
dH/dW [[3.44169138e-13 8.26005930e-14 0.00000000e+00 0.00000000e+00
  1.37667655e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.13376907e-10 2.72104577e-11
  0.00000000e+00 4.53507628e-12]]
dPred/dW [[3.82878243e-02 1.73638204e-13 3.82878243e-02]]


dL/dPred [0.07970942]
dPred/dH [[-0.1237076  0.1269751]]
dH/dW [[6.64937638e-09 1.56455915

dL/dPred [0.07875907]
dPred/dH [[-0.12276796  0.12600178]]
dH/dW [[3.21964677e-13 7.72715225e-14 0.00000000e+00 0.00000000e+00
  1.28785871e-14 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.06110827e-10 2.54665986e-11
  0.00000000e+00 4.24443309e-12]]
dPred/dW [[3.78287868e-02 1.60561754e-13 3.78287868e-02]]


dL/dPred [0.07871401]
dPred/dH [[-0.12271186  0.12593264]]
dH/dW [[6.34251496e-09 1.49235646e-09 0.00000000e+00 0.00000000e+00
  3.73089115e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.08955312e-07 9.62247793e-08
  0.00000000e+00 2.40561948e-08]]
dPred/dW [[3.78080290e-02 9.09517333e-10 3.78080290e-02]]


dL/dPred [-0.06577176]
dPred/dH [[-0.10323561  0.10593549]]
dH/dW [[-6.84306007e-09 -2.73722403e-09  0.00000000e+00  0.00000000e+00
   4.56204005e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.51306344e-07 -1.40522538e-07
   0.00000000e+00  2.34204229e-08]]
dPred/dW [[1.45092950e-11 3.18044000e-02 3.18044008e-02]]


Epoch 1000 loss: 0.006
dL/dPred [-0.088

In [1295]:
emily = np.array([-7, -3]) # 128 pounds, 63 inches
frank = np.array([20, 2])  # 155 pounds, 68 inches
p1,h1 = network.feedforward(emily)
p2,h2 = network.feedforward(frank)
print("Emily: %.3f" % p1[0]) # 0.951 - F
print("Frank: %.3f" % p2[0]) # 0.039

Emily: 0.736
Frank: 0.881
